# Copyright 2022 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Partly auto-Generated by cargo-ebuild 0.5.1

EAPI=8

CRATES="
	addr2line-0.17.0
	adler-1.0.2
	ahash-0.7.6
	aho-corasick-0.7.18
	ansi_term-0.11.0
	anyhow-1.0.45
	arrayvec-0.4.12
	atty-0.2.14
	autocfg-1.0.1
	backtrace-0.3.63
	bindgen-0.59.1
	bitflags-1.3.2
	bitvec-0.19.5
	bytemuck-1.7.2
	cc-1.0.72
	cexpr-0.5.0
	cfg-if-1.0.0
	chrono-0.4.19
	clang-sys-1.3.0
	clap-2.33.3
	console-0.15.0
	cpp_demangle-0.3.3
	crc32fast-1.2.1
	crossbeam-channel-0.5.1
	crossbeam-utils-0.8.5
	ctrlc-3.2.1
	dashmap-4.0.2
	encode_unicode-0.3.6
	env_logger-0.8.4
	env_logger-0.9.0
	errno-0.2.8
	errno-dragonfly-0.1.2
	failure-0.1.8
	failure_derive-0.1.8
	fallible-iterator-0.2.0
	flate2-1.0.22
	funty-1.1.0
	getrandom-0.2.3
	gimli-0.26.1
	glob-0.3.0
	goblin-0.4.3
	hashbrown-0.11.2
	heck-0.3.3
	hermit-abi-0.1.19
	humantime-2.1.0
	indexmap-1.7.0
	indicatif-0.16.2
	inferno-0.10.8
	itoa-0.4.8
	kernel32-sys-0.2.2
	lazy_static-1.4.0
	lazycell-1.3.0
	libc-0.2.107
	libloading-0.7.1
	libm-0.2.1
	libproc-0.10.0
	log-0.4.14
	lru-0.7.0
	mach-0.0.5
	mach-0.3.2
	mach_o_sys-0.1.1
	memchr-2.4.1
	memmap-0.7.0
	memoffset-0.6.4
	miniz_oxide-0.4.4
	nix-0.23.0
	nodrop-0.1.14
	nom-6.1.2
	num-format-0.4.0
	num-integer-0.1.44
	num-traits-0.2.14
	num_cpus-1.13.0
	number_prefix-0.4.0
	object-0.27.1
	once_cell-1.8.0
	peeking_take_while-0.1.2
	plain-0.2.3
	ppv-lite86-0.2.15
	proc-macro-error-1.0.4
	proc-macro-error-attr-1.0.4
	proc-macro2-1.0.32
	proc-maps-0.2.0
	quick-xml-0.22.0
	quote-1.0.10
	radium-0.5.3
	rand-0.8.4
	rand_chacha-0.3.1
	rand_core-0.6.3
	rand_distr-0.4.2
	rand_hc-0.3.1
	read-process-memory-0.1.3
	redox_syscall-0.2.10
	regex-1.5.4
	regex-syntax-0.6.25
	remoteprocess-0.4.7
	remove_dir_all-0.5.3
	rgb-0.8.29
	rustc-demangle-0.1.21
	rustc-hash-1.1.0
	ryu-1.0.5
	scroll-0.10.2
	scroll_derive-0.10.5
	serde-1.0.130
	serde_derive-1.0.130
	serde_json-1.0.69
	shlex-1.1.0
	smallvec-1.7.0
	stable_deref_trait-1.2.0
	str_stack-0.1.0
	strsim-0.8.0
	structopt-0.3.25
	structopt-derive-0.4.18
	syn-1.0.81
	synstructure-0.12.6
	tap-1.0.1
	tempfile-3.2.0
	term_size-0.3.2
	termcolor-1.1.2
	terminal_size-0.1.17
	termios-0.3.3
	textwrap-0.11.0
	time-0.1.44
	unicode-segmentation-1.8.0
	unicode-width-0.1.9
	unicode-xid-0.2.2
	vec_map-0.8.2
	version_check-0.9.3
	wasi-0.10.0+wasi-snapshot-preview1
	which-3.1.1
	winapi-0.2.8
	winapi-0.3.9
	winapi-build-0.1.1
	winapi-i686-pc-windows-gnu-0.4.0
	winapi-util-0.1.5
	winapi-x86_64-pc-windows-gnu-0.4.0
	wyz-0.2.0
"

inherit cargo

DESCRIPTION="Sampling profiler for Python programs"
# Double check the homepage as the cargo_metadata crate
# does not provide this value so instead repository is used
HOMEPAGE="https://github.com/benfred/py-spy"
SRC_URI="
	$(cargo_crate_uris)
	https://github.com/benfred/py-spy/archive/refs/tags/v0.3.11.tar.gz -> ${P}.tar.gz
"

# License set may be more restrictive as OR is not respected
# use cargo-license for a more accurate license picture
LICENSE="0BSD Apache-2.0 Apache-2.0-with-LLVM-exceptions BSD BSD-2 Boost-1.0 CDDL ISC MIT Unlicense ZLIB"
SLOT="0"
KEYWORDS="~amd64"

DEPEND="sys-libs/libunwind"
